# Generated by Django 3.1.5 on 2021-04-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_queryblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryblog',
            name='password',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
